### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by anandhiray** [bostankhan6/SRE-HAN#1]
Can you please let me know how to use it to train using my dataset? Thank you!

**Comment by bostankhan6** [comment]
You can try the training method provided in the official repositories of EDSR and HAN super-resolution networks:

https://github.com/sanghyun-son/EDSR-PyTorch
https://github.com/wwlCape/HAN

The same method of training will work for my code too.

**Comment by anandhiray** [comment]
Thank you!
