### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by anandhiray** [bostankhan6/SRE-HAN#2]
When I tried to train with my dataset, it says: ModuleNotFoundError: No module named 'model.vdsr'.

How do I fix that? 

Thanks!

**Comment by bostankhan6** [comment]
You can try the training method provided in the official repositories of EDSR and HAN super-resolution networks:

https://github.com/sanghyun-son/EDSR-PyTorch
https://github.com/wwlCape/HAN

The same method of training will work for my code too.

**Comment by anandhiray** [comment]
Thank  you!
